/* canvas: src/components/LanguageProvider.jsx
   desc: Provider de Linguagem Original.
   note: Contém o dicionário completo de traduções e exporta useTranslations.
*/
import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  pt: {
    // Layout
    nav_dashboard: "Central",
    nav_dashboard_desc: "Seu centro de comando",
    nav_chat: "Prana AI",
    nav_chat_desc: "Inteligência conversacional",
    nav_sankalpa: "Sankalpa",
    nav_sankalpa_desc: "Sua intenção e propósito",
    nav_cronos: "Cronos",
    nav_cronos_desc: "Planejamento temporal",
    nav_cosmos: "Cosmos",
    nav_cosmos_desc: "Universo temporal",
    nav_diario: "Diário de Bordo",
    nav_diario_desc: "Seu mapa pessoal",
    nav_papyrus: "Papyrus",
    nav_papyrus_desc: "Ideias e reflexões",
    nav_neural: "Neural",
    nav_neural_desc: "Conexões mentais",
    nav_coletivo: "Coletivo",
    nav_coletivo_desc: "Harmonia coletiva",
    nav_matrix: "Matrix",
    nav_matrix_desc: "Dados estruturados",
    nav_flux: "Flux",
    nav_flux_desc: "Fluxo visual",
    nav_settings: "Configurações",
    nav_settings_desc: "Ajustes e preferências",
    nav_nexus: "Nexus",
    nav_nexus_desc: "Tarefas conectadas e fluxos de trabalho",
    menu_about: "Sobre o Prana.ai",
    menu_admin_menu: "Configurações do Menu",
    menu_admin_audit: "Auditoria do Sistema",
    menu_user_settings: "Configurações & Conta",
    tooltip_language: "Idioma",
    tooltip_language_desc: "Selecione o idioma da interface",
    tooltip_themes: "Temas",
    tooltip_themes_desc: "Personalize sua experiência",
    themes_title: "ATMOSFERAS",
    animations_label: "Animações",
    fab_ai_button_title: "Conversar com Ash",
    language_pt: "Português (BR)",
    language_en: "English (US)",
    language_es: "Español (ES)",

    // Página de Configurações
    settings_title: "Configurações",
    settings_subtitle: "Personalize sua experiência no Prana.ai.",
    appearance_title: "Aparência",
    appearance_theme_label: "Tema Visual",
    appearance_animations_label: "Animações da Interface",
    agent_title: "Agente Ash",
    agent_astrology_label: "Astrologia e Human Design",
    agent_astrology_desc: "Permitir que Ash acesse seus dados de nascimento para insights.",
    agent_energy_label: "Insights de Energia e Ciclos",
    agent_energy_desc: "Permitir que Ash analise sua energia diária e ciclos.",
    language_account_title: "Idioma & Conta",
    language_label: "Idioma",
    language_soon: "Em breve",
    session_label: "Sessão",
    session_logout_button: "Desconectar",
    toast_agent_settings_success: "Configuração do agente salva!",
    toast_agent_settings_error: "Erro ao salvar configuração.",

    // Diário de Bordo
    diary_title: "Diário de Bordo",
    diary_subtitle: "Seu mapa pessoal de alinhamento e produtividade.",
    sankalpa_card_title: "Sankalpa - Suas Intenções",
    sankalpa_no_intentions: "Nenhuma intenção definida.",
    sankalpa_create_first: "Criar minha primeira intenção",
    cosmic_profile_title: "Perfil Cósmico",
    cosmic_profile_no_data: "Seus dados de nascimento não foram informados.",
    cosmic_profile_add_data_button: "Informar dados de nascimento",
    menstrual_cycle_title: "Ciclo Menstrual",
    menstrual_cycle_wip: "Funcionalidade de rastreamento do ciclo em desenvolvimento.",
    analytics_title: "Analytics de Energia",
    analytics_wip: "Seus insights de produtividade e energia aparecerão aqui.",
    
    // Modais
    sankalpa_modal_edit_title: "Editar Intenção",
    sankalpa_modal_new_title: "Nova Intenção",
    sankalpa_modal_intention_label: "Intenção",
    sankalpa_modal_intention_placeholder: "Qual é o seu Sankalpa?",
    sankalpa_modal_desc_label: "Descrição (Opcional)",
    sankalpa_modal_desc_placeholder: "Descreva o sentimento ou a visão por trás da sua intenção...",
    sankalpa_modal_toast_empty: "A intenção não pode estar vazia.",
    sankalpa_modal_toast_save_success: "Sankalpa salvo com sucesso!",
    sankalpa_modal_toast_save_error: "Erro ao salvar Sankalpa.",
    sankalpa_modal_toast_delete_success: "Sankalpa removido.",
    sankalpa_modal_toast_delete_error: "Erro ao remover Sankalpa.",
    
    profile_modal_title: "Complete seu Perfil Cósmico",
    profile_modal_subtitle: "Forneça seus dados de nascimento para que o agente Ash possa gerar insights astrológicos e de Human Design personalizados.",
    profile_modal_birthdate: "Data de Nascimento",
    profile_modal_birthtime: "Hora de Nascimento",
    profile_modal_birthlocation: "Local de Nascimento",
    profile_modal_birthlocation_placeholder: "Cidade, Estado, País",
    profile_modal_gender: "Gênero",
    profile_modal_gender_female: "Feminino",
    profile_modal_gender_male: "Masculino",
    profile_modal_gender_other: "Outro / Prefiro não informar",
    profile_modal_gender_desc: "Usado para funcionalidades como o rastreamento do ciclo menstrual.",
    profile_modal_toast_save_success: "Perfil salvo com sucesso!",
    profile_modal_toast_save_error: "Erro ao salvar perfil.",

    // Botões Genéricos
    button_save: "Salvar",
    button_create: "Criar",
    button_cancel: "Cancelar",
    button_delete: "Excluir",
    button_edit: "Editar",

    // Task Connection UI
    task_connections: "Conexões",
    task_connections_desc: "Conectar esta tarefa a outras tarefas",
    select_tasks_to_connect: "Selecionar tarefas para conectar",
    connected_tasks: "Tarefas Conectadas",
    no_connections: "Nenhuma conexão",
    add_connection: "Adicionar Conexão",
    remove_connection: "Remover Conexão",

    // Projetos
    hub_title: "Matriz de Projetos",
    hub_subtitle: "Visão tática e estrutural de todos os seus universos",
    project_create: "Criar Projeto",
    project_edit: "Editar Projeto",
    project_delete: "Deletar Projeto",
    project_archive: "Arquivar Projeto",
    project_empty: "Nenhum projeto encontrado",
    project_subprojects: "Subprojetos",
    project_tasks: "Tarefas",
    project_settings: "Configurações do Projeto",

    // === Tipo de Projeto (Pessoal vs Profissional) ===
    project_type_label: "Tipo de Projeto",
    project_personal: "Pessoal",
    project_personal_desc: "Apenas você vê",
    project_professional: "Profissional",
    project_professional_desc: "Pode compartilhar com time",
    project_share_team: "Compartilhar com time",
    project_select_team: "Selecione um time...",

    // Templates
    save_as_template: "Salvar como Template",
    template_name: "Nome do Template",
    template_description_help: "Escolha exatamente quais dados você quer reutilizar neste template",
    template_field_title: "Título do Projeto",
    template_field_description: "Descrição",
    template_field_tags: "Tags",
    template_field_custom_fields: "Campos Customizados",
    template_field_subtasks: "Estrutura de Tarefas",
    template_field_color: "Cor",
    template_field_icon: "Ícone",
    template_field_settings: "Configurações",
    select_fields_to_save: "Selecione os campos a salvar",
    template_description_placeholder: "Descreva quando usar este template...",
    template_saved_success: "Template salvo com sucesso!",
    use_template: "Usar Template",
    select_template_help: "Selecione um de seus templates para criar um novo projeto",
    no_templates_yet: "Você ainda não tem templates salvos",
    create_template_hint: "Crie um projeto e salve como template!",
    included_data: "Dados que serão inclusos:",
    new_project_name: "Nome do novo projeto",
    enter_project_name: "Ex: Projeto Importante",
    create_from_template: "Criar do Template",
    template_use_case: "Use este template para criar novos projetos rapidamente com a mesma estrutura e configurações",
    template_applied: "Projeto criado a partir do template!",
    error_template_name_required: "Nome do template é obrigatório",
    error_save_template: "Erro ao salvar template",
    error_load_templates: "Erro ao carregar templates",
    error_apply_template: "Erro ao aplicar template",
    error_project_name_required: "Digite o nome do novo projeto",
    used: "Usado",

    // Sidebar Actions
    nav_planner: "Planejador",
    nav_calendar: "Calendário",
    nav_explorer: "Explorer",
    nav_tags: "Tags",
    nav_search: "Busca",
    quick_idea: "Nova Ideia",
    quick_task: "Nova Tarefa",
    quick_project: "Novo Projeto",
    quick_document: "Novo Documento",
    logout: "Sair",

    // Calendário
    month_view: "Visualização Mensal",
    week_view: "Visualização Semanal",
    day_view: "Visualização Diária",
    today_button: "Hoje",
    prev_month: "Mês Anterior",
    next_month: "Próximo Mês",
    add_event: "Adicionar Evento",
    edit_event: "Editar Evento",
    delete_event: "Deletar Evento",
    calendar_empty: "Vazio",
    calendar_no_deadline: "Sem Prazo",
    calendar_all_scheduled: "Tudo agendado.",
    calendar_drop_to_remove: "Solte para remover data",
    calendar_sun: "DOM",
    calendar_mon: "SEG",
    calendar_tue: "TER",
    calendar_wed: "QUA",
    calendar_thu: "QUI",
    calendar_fri: "SEX",
    calendar_sat: "SÁB",

    // Times
    add_member: "Adicionar Membro",
    invite_email: "Convidar por E-mail",
    manage_roles: "Gerenciar Funções",
    leave_team: "Sair do Time",
    team_members: "Membros do Time",
    team_settings: "Configurações do Time",
    invite_member: "Convidar Membro",
    invite_guardian: "Convidar Guardião",
    members_active: "Membros Ativos & Vitalidade",
    email_collaborator: "Email do Colaborador",
    access_permission: "Permissão de Acesso",
    role_admin: "Admin (Líder)",
    role_editor: "Editor (Colaborador)",
    role_viewer: "Observador (Leitor)",
    cancel: "Cancelar",
    send_invite: "Enviar Convite",
    invite_sent: "Convite estelar enviado para {{email}}",
    team_sync_error: "Erro ao sincronizar equipe.",
    gathering_council: "Reunindo o conselho...",

    // Vistas
    kanban_board: "Quadro Kanban",
    sheet_view: "Visualização de Planilha",
    mind_map: "Mapa Mental",
    chain_view: "Visualização em Cadeia",
    doc_editor: "Editor de Documentos",
    inbox_view: "Caixa de Entrada",

    // Abas do Projeto
    tab_overview: "Visão Geral",
    tab_board: "Quadro",
    tab_sheet: "Lista",
    tab_calendar: "Cronograma",
    tab_map: "Mapa Mental",
    tab_nexus: "Nexus",
    tab_files: "Arquivos",
    tab_team: "Equipe",
    tab_settings: "Ajustes",

    // Ações de Tarefa
    add_task: "Adicionar Tarefa",
    edit_task: "Editar Tarefa",
    delete_task: "Deletar Tarefa",
    mark_complete: "Marcar como Concluído",
    add_subtask: "Adicionar Subtarefa",
    task_priority: "Prioridade",
    task_due_date: "Data de Vencimento",
    task_assignee: "Atribuído a",
    task_status: "Status",
    task_description: "Descrição",

    // Modais e Confirmações
    confirm_delete: "Tem certeza que deseja deletar?",
    confirm_delete_desc: "Esta ação não pode ser desfeita.",
    unsaved_changes: "Há mudanças não salvas",
    save_changes: "Salvar Mudanças",
    discard_changes: "Descartar Mudanças",
    close: "Fechar",

    // Validação
    required_field: "Campo obrigatório",
    invalid_email: "E-mail inválido",
    min_length: "Comprimento mínimo: {length}",
    max_length: "Comprimento máximo: {length}",
    password_mismatch: "As senhas não correspondem",
    success: "Sucesso!",
    error: "Erro",
    loading: "Carregando...",
    no_data: "Nenhum dado disponível",

    // Configurações
    appearance: "Aparência",
    account_region: "Conta & Região",
    animations: "Animações Interface",
    animations_desc: "Efeitos de partículas e transições suaves.",
    system_language: "Idioma do Sistema",
    logout_session: "Encerrar Sessão",
    ash_brain: "Cérebro do Ash",
    main_role: "Papel Principal",
    main_role_desc: "Ex: Senior React Dev, Copywriter, Mentor...",
    voice_tone: "Tom de Voz",
    voice_tone_desc: "Ex: Direto, Socrático, Divertido, Formal...",
    tech_stack: "Stack Tecnológica / Contexto",
    tech_stack_desc: "Ex: React, Tailwind, Node.js, Drizzle ORM",
    custom_instructions: "Instruções Customizadas (Lei Suprema)",
    custom_instructions_desc: "Ex: Sempre explique o 'porquê' antes do código...",
    update_brain: "Atualizar Cérebro",
    tuning: "Sintonizando...",

    // Kanban
    kanban_add_note: "Adicionar Nota",
    kanban_todo: "A Fazer",
    kanban_in_progress: "Em Progresso",
    kanban_blocked: "Bloqueado",
    kanban_done: "Concluído",

    // Inbox (Faíscas)
    inbox_title: "Caixa de Entrada",
    inbox_subtitle: "Capture, processe e esvazie sua mente.",
    inbox_zero: "Inbox Zero",
    inbox_zero_desc: "Sua mente está limpa. Use o atalho Ctrl+K para capturar novas ideias.",
    promote_to_task: "Transformar em Tarefa",
    promote_to_project: "Transformar em Projeto",
    promoted_to_task: "Promovido para Tarefa!",
    promoted_to_project: "Expandido para Projeto!",
    promoted_to_task_error: "Erro ao promover.",
    inbox_empty_error: "Erro ao descartar.",
    inbox_loading: "Sintonizando pensamentos...",
    inbox_error: "Erro ao carregar Inbox.",

    // Sheet View
    sheet_title: "Planilha",
    sheet_items_count: "Itens",
    sheet_filter_placeholder: "Filtrar...",
    sheet_show_columns: "Exibir",
    sheet_columns: "Colunas",
    sheet_new_subtask: "Nova Subtarefa",
    sheet_delete_item: "Excluir",
    sheet_new_root_line: "Nova Linha Raiz",
    sheet_select_project: "Selecione um projeto.",
    sheet_task_name: "Tarefa",
    sheet_responsible: "Responsável",
    sheet_status: "Status",
    sheet_priority: "Prioridade",
    sheet_due_date: "Prazo",
    sheet_remove_confirm: "Remover item?",
    sheet_created: "Criado.",
    sheet_error: "Erro.",
    sheet_save_error: "Falha ao salvar.",

    // Mind Map
    mindmap_add_node: "Nó",
    mindmap_title: "Mind Map",
    mindmap_tuning: "Sintonizando frequências...",
    mindmap_saving: "Salvando...",
    mindmap_synced: "Sincronizado",
    mindmap_project_nucleus: "Núcleo do Projeto",
    mindmap_global_consciousness: "Consciência Global",

    // Doc Editor
    doc_editor_loading: "Abrindo o grimório...",
    doc_editor_error_not_found: "Documento não encontrado ou acesso negado.",
    doc_editor_error_loading: "Erro ao carregar documento.",
    doc_editor_save_error: "Falha ao salvar alterações.",
    doc_editor_saving: "Salvando...",
    doc_editor_saved_at: "Salvo às",
    doc_editor_no_title: "Sem Título",
    doc_editor_draft: "Rascunho",
    doc_editor_share: "Compartilhar",
    doc_editor_retry: "Tentar Novamente",
    doc_editor_title_updated: "Título atualizado.",
    
    // Document Type Selection
    doc_type_label: "Tipo de Documento",
    doc_type_note: "Nota",
    doc_type_diary: "Diário",
    doc_type_agreement: "Acordo",
    doc_type_manifest: "Manifesto",
    doc_type_guide: "Guia",
    doc_type_other: "Outro",
    
    // Diary Fields (when documentType='diary')
    diary_energy_label: "Nível de Energia",
    diary_energy_1: "Muito Baixa",
    diary_energy_2: "Baixa",
    diary_energy_3: "Média",
    diary_energy_4: "Alta",
    diary_energy_5: "Muito Alta",
    diary_mood_label: "Humor",
    diary_mood_calm: "Calma",
    diary_mood_joy: "Alegria",
    diary_mood_focus: "Foco",
    diary_mood_creativity: "Criatividade",
    diary_mood_anxiety: "Ansiedade",
    diary_mood_confusion: "Confusão",
    diary_mood_gratitude: "Gratidão",
    diary_mood_sadness: "Tristeza",
    diary_tags_label: "Tags",
    diary_tags_placeholder: "Adicionar tag...",
    diary_insights_label: "Insights Adicionais",
    diary_insights_placeholder: "Anotações extras...",
    diary_private: "Privado (apenas você vê)",
    diary_saved_success: "Diário salvo com sucesso!",

    // Chain View (Nexus)
    chain_loading: "Mapeando o cosmos...",
    chain_title: "Nexus",
    chain_subtitle: "Mapa de Dependências",
    chain_error_mapping: "Erro ao mapear constelação.",
    chain_error_connection: "Falha na conexão.",
    chain_link_created: "Vínculo estelar criado.",
    chain_drag_to_connect: "Arraste para conectar",

    // Planner View
    planner_title: "Matriz Temporal",
    planner_sync_error: "Falha na sincronização temporal.",
    planner_save_error: "Erro ao salvar movimento.",
    planner_today: "Hoje",

    // Tag Canvas View
    tag_canvas_loading: "Mapeando #",
    tag_canvas_no_tag: "Selecione uma tag",
    tag_canvas_virtual_context: "Contexto Virtual",
    tag_canvas_items: "Itens",
    tag_canvas_related_projects: "Projetos Relacionados",
    tag_canvas_tasks_actions: "Tarefas & Ações",
    tag_canvas_knowledge_docs: "Conhecimento (Docs)",
    tag_canvas_no_items: "Nenhum item marcado com #",

    // List View
    list_view_loading: "Carregando...",
    list_view_status_todo: "A Fazer",
    list_view_status_doing: "Fazendo",
    list_view_status_review: "Revisão",
    list_view_status_done: "Concluído",
    list_view_error_loading: "Erro ao carregar lista:",

    // Sankalpa View
    sankalpa_greeting: "Qual é a sua intenção para agora?",
    sankalpa_create_something: "Criar Algo",
    sankalpa_search: "Buscar...",
    sankalpa_press_space: "Pressione Espaço para falar com Ash",

    // Dashboard View  
    dashboard_intention_day: "Intenção do Dia",
    dashboard_today_velocity: "Velocidade (Hoje)",
    dashboard_project_matrix: "Matriz de Projetos",
    dashboard_moon_sign: "Lua em Escorpião",
    dashboard_advice: "O invisível ganha forma. Aprofunde suas raízes.",
    dashboard_energy_summary: "Energia densa. Ideal para foco.",
    dashboard_favorable_energy: "Energia favorável para introspecção.",

    // Chat View
    chat_focus_session: "Sessão de Foco",
    chat_new_conversation: "Nova Conversa",
    chat_attach_file: "Anexar arquivo",
    chat_send_message: "Conversar com o Prana...",
    chat_prana_ai: "Prana AI 3.0 • OpenAI Integrado",
    
    // SideChat
    sidechat_ash_title: "Ash",
    sidechat_neural_interface: "Interface Neural",
    sidechat_clear_memory: "Limpar Memória",
    sidechat_focus_indicator: "Em Foco",
    sidechat_context_label: "Contexto",
    sidechat_thinking: "Pensando...",
    sidechat_neural_connected: "Conexão neural estabelecida.",
    sidechat_awaiting_input: "Aguardando input...",
    sidechat_placeholder_default: "Converse com Ash...",
    sidechat_placeholder_context: "Sobre:",
    
    // Holistic Context Indicators (Novos)
    holistic_energy_indicator: "Energia Física",
    holistic_mood_indicator: "Estados Emocionais",
    holistic_tags_label: "Tópicos em Foco",
    holistic_astrology_indicator: "Cosmos",
    holistic_menstrual_indicator: "Ciclo Menstrual",
    holistic_menstrual_menstrual: "Menstrual",
    holistic_menstrual_folicular: "Folicular",
    holistic_menstrual_ovulatory: "Ovulatória",
    holistic_menstrual_luteal: "Lútea",
    
    // Ash Holistic Integration
    ash_energy_low: "⚠️ Sua energia está baixa. Considere fazer uma pausa restaurativa.",
    ash_energy_high: "✨ Sua energia está alta! Aproveite para projetos desafiadores.",
    ash_anxiety_detected: "🧘 Você tem vivido com ansiedade. Tente meditação ou movimento.",
    ash_pattern_focus: "📊 Você tem focado muito em \"%s\". Explore outros aspectos.",
    ash_consistency_achievement: "🏆 Parabéns por sua consistência! Você registrou %d diários.",
    ash_context_energy: "Energia média: %.1f/5",
    ash_context_mood: "Humor predominante: %s",
    ash_context_diaries: "Total de diários: %d",
    ash_context_header: "Contexto Holístico",
    ash_suggestions_title: "Sugestões Personalizadas",
    ash_loading_context: "Analisando seu contexto holístico...",
    ash_error_context: "Erro ao carregar contexto holístico.",
    
    // Sidebar & Layout
    sidebar_explorer: "EXPLORADOR",
    sidebar_tags: "TAGS",
    sidebar_system_active: "System Active",
    sidebar_version: "v10.0 Release",
  },
  en: {
    // Layout
    nav_dashboard: "Dashboard",
    nav_dashboard_desc: "Your command center",
    nav_chat: "Prana AI",
    nav_chat_desc: "Conversational intelligence",
    nav_sankalpa: "Sankalpa",
    nav_sankalpa_desc: "Your intention and purpose",
    nav_cronos: "Cronos",
    nav_cronos_desc: "Temporal planning",
    nav_cosmos: "Cosmos",
    nav_cosmos_desc: "Temporal universe",
    nav_diario: "Logbook",
    nav_diario_desc: "Your personal map",
    nav_papyrus: "Papyrus",
    nav_papyrus_desc: "Ideas and reflections",
    nav_neural: "Neural",
    nav_neural_desc: "Mental connections",
    nav_coletivo: "Collective",
    nav_coletivo_desc: "Collective harmony",
    nav_matrix: "Matrix",
    nav_matrix_desc: "Structured data",
    nav_flux: "Flux",
    nav_flux_desc: "Visual workflow",
    nav_settings: "Settings",
    nav_settings_desc: "Adjustments and preferences",
    nav_nexus: "Nexus",
    nav_nexus_desc: "Connected tasks and workflows",
    menu_about: "About Prana.ai",
    menu_admin_menu: "Menu Settings",
    menu_admin_audit: "System Audit",
    menu_user_settings: "Settings & Account",
    tooltip_language: "Language",
    tooltip_language_desc: "Select the interface language",
    tooltip_themes: "Themes",
    tooltip_themes_desc: "Customize your experience",
    themes_title: "ATMOSPHERES",
    animations_label: "Animations",
    fab_ai_button_title: "Chat with Ash",
    language_pt: "Português (BR)",
    language_en: "English (US)",
    language_es: "Español (ES)",

    // Settings Page
    settings_title: "Settings",
    settings_subtitle: "Customize your Prana.ai experience.",
    appearance_title: "Appearance",
    appearance_theme_label: "Visual Theme",
    appearance_animations_label: "Interface Animations",
    agent_title: "Agent Ash",
    agent_astrology_label: "Astrology and Human Design",
    agent_astrology_desc: "Allow Ash to access your birth data for insights.",
    agent_energy_label: "Energy and Cycle Insights",
    agent_energy_desc: "Allow Ash to analyze your daily energy and cycles.",
    language_account_title: "Language & Account",
    language_label: "Language",
    language_soon: "Soon",
    session_label: "Session",
    session_logout_button: "Log Out",
    toast_agent_settings_success: "Agent settings saved!",
    toast_agent_settings_error: "Error saving settings.",

    // Logbook
    diary_title: "Logbook",
    diary_subtitle: "Your personal map of alignment and productivity.",
    sankalpa_card_title: "Sankalpa - Your Intentions",
    sankalpa_no_intentions: "No intentions defined.",
    sankalpa_create_first: "Create my first intention",
    cosmic_profile_title: "Cosmic Profile",
    cosmic_profile_no_data: "Your birth data has not been provided.",
    cosmic_profile_add_data_button: "Enter birth data",
    menstrual_cycle_title: "Menstrual Cycle",
    menstrual_cycle_wip: "Cycle tracking feature under development.",
    analytics_title: "Energy Analytics",
    analytics_wip: "Your productivity and energy insights will appear here.",
    
    // Modals
    sankalpa_modal_edit_title: "Edit Intention",
    sankalpa_modal_new_title: "New Intention",
    sankalpa_modal_intention_label: "Intention",
    sankalpa_modal_intention_placeholder: "What is your Sankalpa?",
    sankalpa_modal_desc_label: "Description (Optional)",
    sankalpa_modal_desc_placeholder: "Describe the feeling or vision behind your intention...",
    sankalpa_modal_toast_empty: "Intention cannot be empty.",
    sankalpa_modal_toast_save_success: "Sankalpa saved successfully!",
    sankalpa_modal_toast_save_error: "Error saving Sankalpa.",
    sankalpa_modal_toast_delete_success: "Sankalpa removed.",
    sankalpa_modal_toast_delete_error: "Error removing Sankalpa.",

    profile_modal_title: "Complete Your Cosmic Profile",
    profile_modal_subtitle: "Provide your birth data so agent Ash can generate personalized astrological and Human Design insights.",
    profile_modal_birthdate: "Birth Date",
    profile_modal_birthtime: "Birth Time",
    profile_modal_birthlocation: "Birth Location",
    profile_modal_birthlocation_placeholder: "City, State, Country",
    profile_modal_gender: "Gender",
    profile_modal_gender_female: "Female",
    profile_modal_gender_male: "Male",
    profile_modal_gender_other: "Other / Prefer not to say",
    profile_modal_gender_desc: "Used for features like menstrual cycle tracking.",
    profile_modal_toast_save_success: "Profile saved successfully!",
    profile_modal_toast_save_error: "Error saving profile.",
    
    // Generic Buttons
    button_save: "Save",
    button_create: "Create",
    button_cancel: "Cancel",
    button_delete: "Delete",
    button_edit: "Edit",

    // Task Connection UI
    task_connections: "Connections",
    task_connections_desc: "Connect this task to other tasks",
    select_tasks_to_connect: "Select tasks to connect",
    connected_tasks: "Connected Tasks",
    no_connections: "No connections",
    add_connection: "Add Connection",
    remove_connection: "Remove Connection",

    // Projects
    hub_title: "Project Matrix",
    hub_subtitle: "Tactical and structural view of all your universes",
    project_create: "Create Project",
    project_edit: "Edit Project",
    project_delete: "Delete Project",
    project_archive: "Archive Project",
    project_empty: "No projects found",
    project_subprojects: "Subprojects",
    project_tasks: "Tasks",
    project_settings: "Project Settings",

    // === Project Type (Personal vs Professional) ===
    project_type_label: "Project Type",
    project_personal: "Personal",
    project_personal_desc: "Only you can see it",
    project_professional: "Professional",
    project_professional_desc: "Share with your team",
    project_share_team: "Share with team",
    project_select_team: "Select a team...",

    // Templates
    save_as_template: "Save as Template",
    template_name: "Template Name",
    template_description_help: "Choose exactly which data you want to reuse in this template",
    template_field_title: "Project Title",
    template_field_description: "Description",
    template_field_tags: "Tags",
    template_field_custom_fields: "Custom Fields",
    template_field_subtasks: "Task Structure",
    template_field_color: "Color",
    template_field_icon: "Icon",
    template_field_settings: "Settings",
    select_fields_to_save: "Select fields to save",
    template_description_placeholder: "Describe when to use this template...",
    template_saved_success: "Template saved successfully!",
    use_template: "Use Template",
    select_template_help: "Select one of your templates to create a new project",
    no_templates_yet: "You don't have any saved templates yet",
    create_template_hint: "Create a project and save it as a template!",
    included_data: "Data that will be included:",
    new_project_name: "New project name",
    enter_project_name: "Ex: Important Project",
    create_from_template: "Create from Template",
    template_use_case: "Use this template to quickly create new projects with the same structure and settings",
    template_applied: "Project created from template!",
    error_template_name_required: "Template name is required",
    error_save_template: "Error saving template",
    error_load_templates: "Error loading templates",
    error_apply_template: "Error applying template",
    error_project_name_required: "Enter the new project name",
    used: "Used",

    // Sidebar Actions
    nav_planner: "Planner",
    nav_calendar: "Calendar",
    nav_explorer: "Explorer",
    nav_tags: "Tags",
    nav_search: "Search",
    quick_idea: "New Idea",
    quick_task: "New Task",
    quick_project: "New Project",
    quick_document: "New Document",
    logout: "Logout",

    // Calendar
    month_view: "Month View",
    week_view: "Week View",
    day_view: "Day View",
    today_button: "Today",
    prev_month: "Previous Month",
    next_month: "Next Month",
    add_event: "Add Event",
    edit_event: "Edit Event",
    delete_event: "Delete Event",
    calendar_empty: "Empty",
    calendar_no_deadline: "No Deadline",
    calendar_all_scheduled: "Everything scheduled.",
    calendar_drop_to_remove: "Drop to remove date",
    calendar_sun: "SUN",
    calendar_mon: "MON",
    calendar_tue: "TUE",
    calendar_wed: "WED",
    calendar_thu: "THU",
    calendar_fri: "FRI",
    calendar_sat: "SAT",

    // Teams
    add_member: "Add Member",
    invite_email: "Invite by Email",
    manage_roles: "Manage Roles",
    leave_team: "Leave Team",
    team_members: "Team Members",
    team_settings: "Team Settings",
    invite_member: "Invite Member",
    invite_guardian: "Invite Guardian",
    members_active: "Active Members & Vitality",
    email_collaborator: "Collaborator Email",
    access_permission: "Access Permission",
    role_admin: "Admin (Leader)",
    role_editor: "Editor (Collaborator)",
    role_viewer: "Observer (Reader)",
    cancel: "Cancel",
    send_invite: "Send Invite",
    invite_sent: "Stellar invite sent to {{email}}",
    team_sync_error: "Error syncing team.",
    gathering_council: "Gathering the council...",

    // Views
    kanban_board: "Kanban Board",
    sheet_view: "Sheet View",
    mind_map: "Mind Map",
    chain_view: "Chain View",
    doc_editor: "Document Editor",
    inbox_view: "Inbox",

    // Project Tabs
    tab_overview: "Overview",
    tab_board: "Board",
    tab_sheet: "List",
    tab_calendar: "Schedule",
    tab_map: "Mind Map",
    tab_nexus: "Nexus",
    tab_files: "Files",
    tab_team: "Team",
    tab_settings: "Settings",

    // Task Actions
    add_task: "Add Task",
    edit_task: "Edit Task",
    delete_task: "Delete Task",
    mark_complete: "Mark as Complete",
    add_subtask: "Add Subtask",
    task_priority: "Priority",
    task_due_date: "Due Date",
    task_assignee: "Assigned to",
    task_status: "Status",
    task_description: "Description",

    // Modals and Confirmations
    confirm_delete: "Are you sure you want to delete?",
    confirm_delete_desc: "This action cannot be undone.",
    unsaved_changes: "There are unsaved changes",
    save_changes: "Save Changes",
    discard_changes: "Discard Changes",
    close: "Close",

    // Validation
    required_field: "Required field",
    invalid_email: "Invalid email",
    min_length: "Minimum length: {length}",
    max_length: "Maximum length: {length}",
    password_mismatch: "Passwords do not match",
    success: "Success!",
    error: "Error",
    loading: "Loading...",
    no_data: "No data available",

    // Settings
    appearance: "Appearance",
    account_region: "Account & Region",
    animations: "Interface Animations",
    animations_desc: "Particle effects and smooth transitions.",
    system_language: "System Language",
    logout_session: "End Session",
    ash_brain: "Ash's Brain",
    main_role: "Main Role",
    main_role_desc: "Ex: Senior React Dev, Copywriter, Mentor...",
    voice_tone: "Voice Tone",
    voice_tone_desc: "Ex: Direct, Socratic, Fun, Formal...",
    tech_stack: "Tech Stack / Context",
    tech_stack_desc: "Ex: React, Tailwind, Node.js, Drizzle ORM",
    custom_instructions: "Custom Instructions (Supreme Law)",
    custom_instructions_desc: "Ex: Always explain the 'why' before code...",
    update_brain: "Update Brain",
    tuning: "Tuning...",

    // Kanban
    kanban_add_note: "Add Note",
    kanban_todo: "To Do",
    kanban_in_progress: "In Progress",
    kanban_blocked: "Blocked",
    kanban_done: "Done",

    // Inbox (Sparks)
    inbox_title: "Inbox",
    inbox_subtitle: "Capture, process and clear your mind.",
    inbox_zero: "Inbox Zero",
    inbox_zero_desc: "Your mind is clean. Use Ctrl+K shortcut to capture new ideas.",
    promote_to_task: "Promote to Task",
    promote_to_project: "Promote to Project",
    promoted_to_task: "Promoted to Task!",
    promoted_to_project: "Expanded to Project!",
    promoted_to_task_error: "Error promoting.",
    inbox_empty_error: "Error discarding.",
    inbox_loading: "Tuning thoughts...",
    inbox_error: "Error loading Inbox.",

    // Sheet View
    sheet_title: "Sheet",
    sheet_items_count: "Items",
    sheet_filter_placeholder: "Filter...",
    sheet_show_columns: "Show",
    sheet_columns: "Columns",
    sheet_new_subtask: "New Subtask",
    sheet_delete_item: "Delete",
    sheet_new_root_line: "New Root Line",
    sheet_select_project: "Select a project.",
    sheet_task_name: "Task",
    sheet_responsible: "Responsible",
    sheet_status: "Status",
    sheet_priority: "Priority",
    sheet_due_date: "Due Date",
    sheet_remove_confirm: "Remove item?",
    sheet_created: "Created.",
    sheet_error: "Error.",
    sheet_save_error: "Failed to save.",

    // Mind Map
    mindmap_add_node: "Node",
    mindmap_title: "Mind Map",
    mindmap_tuning: "Tuning frequencies...",
    mindmap_saving: "Saving...",
    mindmap_synced: "Synced",
    mindmap_project_nucleus: "Project Nucleus",
    mindmap_global_consciousness: "Global Consciousness",

    // Doc Editor
    doc_editor_loading: "Opening the grimoire...",
    doc_editor_error_not_found: "Document not found or access denied.",
    doc_editor_error_loading: "Error loading document.",
    doc_editor_save_error: "Failed to save changes.",
    doc_editor_saving: "Saving...",
    doc_editor_saved_at: "Saved at",
    doc_editor_no_title: "Untitled",
    doc_editor_draft: "Draft",
    doc_editor_share: "Share",
    doc_editor_retry: "Try Again",
    doc_editor_title_updated: "Title updated.",
    
    // Document Type Selection
    doc_type_label: "Document Type",
    doc_type_note: "Note",
    doc_type_diary: "Diary",
    doc_type_agreement: "Agreement",
    doc_type_manifest: "Manifest",
    doc_type_guide: "Guide",
    doc_type_other: "Other",
    
    // Diary Fields (when documentType='diary')
    diary_energy_label: "Energy Level",
    diary_energy_1: "Very Low",
    diary_energy_2: "Low",
    diary_energy_3: "Medium",
    diary_energy_4: "High",
    diary_energy_5: "Very High",
    diary_mood_label: "Mood",
    diary_mood_calm: "Calm",
    diary_mood_joy: "Joy",
    diary_mood_focus: "Focus",
    diary_mood_creativity: "Creativity",
    diary_mood_anxiety: "Anxiety",
    diary_mood_confusion: "Confusion",
    diary_mood_gratitude: "Gratitude",
    diary_mood_sadness: "Sadness",
    diary_tags_label: "Tags",
    diary_tags_placeholder: "Add tag...",
    diary_insights_label: "Additional Insights",
    diary_insights_placeholder: "Extra notes...",
    diary_private: "Private (only you see)",
    diary_saved_success: "Diary saved successfully!",

    // Chain View (Nexus)
    chain_loading: "Mapping the cosmos...",
    chain_title: "Nexus",
    chain_subtitle: "Dependency Map",
    chain_error_mapping: "Error mapping constellation.",
    chain_error_connection: "Connection failed.",
    chain_link_created: "Stellar link created.",
    chain_drag_to_connect: "Drag to connect",

    // Planner View
    planner_title: "Time Matrix",
    planner_sync_error: "Temporal synchronization failed.",
    planner_save_error: "Error saving movement.",
    planner_today: "Today",

    // Tag Canvas View
    tag_canvas_loading: "Mapping #",
    tag_canvas_no_tag: "Select a tag",
    tag_canvas_virtual_context: "Virtual Context",
    tag_canvas_items: "Items",
    tag_canvas_related_projects: "Related Projects",
    tag_canvas_tasks_actions: "Tasks & Actions",
    tag_canvas_knowledge_docs: "Knowledge (Docs)",
    tag_canvas_no_items: "No items tagged with #",

    // List View
    list_view_loading: "Loading...",
    list_view_status_todo: "To Do",
    list_view_status_doing: "Doing",
    list_view_status_review: "Review",
    list_view_status_done: "Done",
    list_view_error_loading: "Error loading list:",

    // Sankalpa View
    sankalpa_greeting: "What is your intention right now?",
    sankalpa_create_something: "Create Something",
    sankalpa_search: "Search...",
    sankalpa_press_space: "Press Space to speak with Ash",

    // Dashboard View  
    dashboard_intention_day: "Intention of the Day",
    dashboard_today_velocity: "Velocity (Today)",
    dashboard_project_matrix: "Project Matrix",
    dashboard_moon_sign: "Moon in Scorpio",
    dashboard_advice: "The invisible takes form. Deepen your roots.",
    dashboard_energy_summary: "Dense energy. Ideal for focus.",
    dashboard_favorable_energy: "Favorable energy for introspection.",

    // Chat View
    chat_focus_session: "Focus Session",
    chat_new_conversation: "New Conversation",
    chat_attach_file: "Attach file",
    chat_send_message: "Talk to Prana...",
    chat_prana_ai: "Prana AI 3.0 • OpenAI Integrated",
    
    // SideChat
    sidechat_ash_title: "Ash",
    sidechat_neural_interface: "Neural Interface",
    sidechat_clear_memory: "Clear Memory",
    sidechat_focus_indicator: "In Focus",
    sidechat_context_label: "Context",
    sidechat_thinking: "Thinking...",
    sidechat_neural_connected: "Neural connection established.",
    sidechat_awaiting_input: "Awaiting input...",
    sidechat_placeholder_default: "Talk to Ash...",
    sidechat_placeholder_context: "About:",
    
    // Holistic Context Indicators (New)
    holistic_energy_indicator: "Physical Energy",
    holistic_mood_indicator: "Emotional States",
    holistic_tags_label: "Focus Topics",
    holistic_astrology_indicator: "Cosmos",
    holistic_menstrual_indicator: "Menstrual Cycle",
    holistic_menstrual_menstrual: "Menstrual",
    holistic_menstrual_folicular: "Follicular",
    holistic_menstrual_ovulatory: "Ovulatory",
    holistic_menstrual_luteal: "Luteal",
    
    // Sidebar & Layout
    sidebar_explorer: "EXPLORER",
    sidebar_tags: "TAGS",
    sidebar_system_active: "System Active",
    sidebar_version: "v10.0 Release",
  },
  es: {
    // Layout
    nav_dashboard: "Central",
    nav_dashboard_desc: "Tu centro de mando",
    nav_chat: "Prana AI",
    nav_chat_desc: "Inteligencia conversacional",
    nav_sankalpa: "Sankalpa",
    nav_sankalpa_desc: "Tu intención y propósito",
    nav_cronos: "Cronos",
    nav_cronos_desc: "Planificación temporal",
    nav_cosmos: "Cosmos",
    nav_cosmos_desc: "Universo temporal",
    nav_diario: "Bitácora",
    nav_diario_desc: "Tu mapa personal",
    nav_papyrus: "Papyrus",
    nav_papyrus_desc: "Ideas y reflexiones",
    nav_neural: "Neural",
    nav_neural_desc: "Conexiones mentales",
    nav_coletivo: "Coletivo",
    nav_coletivo_desc: "Armonía colectiva",
    nav_matrix: "Matrix",
    nav_matrix_desc: "Datos estructurados",
    nav_flux: "Flux",
    nav_flux_desc: "Flujo de trabajo visual",
    nav_settings: "Configuración",
    nav_settings_desc: "Ajustes y preferencias",
    nav_nexus: "Nexus",
    nav_nexus_desc: "Tareas conectadas y flujos de trabajo",
    menu_about: "Sobre Prana.ai",
    menu_admin_menu: "Configuración del Menú",
    menu_admin_audit: "Auditoría del Sistema",
    menu_user_settings: "Configuración & Cuenta",
    tooltip_language: "Idioma",
    tooltip_language_desc: "Selecciona el idioma de la interfaz",
    tooltip_themes: "Temas",
    tooltip_themes_desc: "Personaliza tu experiencia",
    themes_title: "ATMÓSFERAS",
    animations_label: "Animaciones",
    fab_ai_button_title: "Chatear con Ash",
    language_pt: "Português (BR)",
    language_en: "English (US)",
    language_es: "Español (ES)",

    // Página de Configuración
    settings_title: "Configuración",
    settings_subtitle: "Personaliza tu experiencia en Prana.ai.",
    appearance_title: "Apariencia",
    appearance_theme_label: "Tema Visual",
    appearance_animations_label: "Animaciones de la Interfaz",
    agent_title: "Agente Ash",
    agent_astrology_label: "Astrología y Diseño Humano",
    agent_astrology_desc: "Permitir que Ash acceda a tus datos de nacimiento para obtener ideas.",
    agent_energy_label: "Ideas de Energía y Ciclos",
    agent_energy_desc: "Permitir que Ash analice tu energía y ciclos diarios.",
    language_account_title: "Idioma & Cuenta",
    language_label: "Idioma",
    language_soon: "Pronto",
    session_label: "Sesión",
    session_logout_button: "Cerrar Sesión",
    toast_agent_settings_success: "¡Configuración del agente guardada!",
    toast_agent_settings_error: "Error al guardar la configuración.",

    // Bitácora
    diary_title: "Bitácora",
    diary_subtitle: "Tu mapa personal de alineación y productividad.",
    sankalpa_card_title: "Sankalpa - Tus Intenciones",
    sankalpa_no_intentions: "No hay intenciones definidas.",
    sankalpa_create_first: "Crear mi primera intención",
    cosmic_profile_title: "Perfil Cósmico",
    cosmic_profile_no_data: "No has proporcionado tus datos de nacimiento.",
    cosmic_profile_add_data_button: "Introducir datos de nacimiento",
    menstrual_cycle_title: "Ciclo Menstrual",
    menstrual_cycle_wip: "Función de seguimiento del ciclo en desarrollo.",
    analytics_title: "Análisis de Energía",
    analytics_wip: "Tus ideas sobre productividad y energía aparecerán aquí.",

    // Modales
    sankalpa_modal_edit_title: "Editar Intención",
    sankalpa_modal_new_title: "Nueva Intención",
    sankalpa_modal_intention_label: "Intención",
    sankalpa_modal_intention_placeholder: "¿Cuál es tu Sankalpa?",
    sankalpa_modal_desc_label: "Descripción (Opcional)",
    sankalpa_modal_desc_placeholder: "Describe el sentimiento o la visión detrás de tu intención...",
    sankalpa_modal_toast_empty: "La intención no puede estar vacía.",
    sankalpa_modal_toast_save_success: "¡Sankalpa guardado con éxito!",
    sankalpa_modal_toast_save_error: "Error al guardar el Sankalpa.",
    sankalpa_modal_toast_delete_success: "Sankalpa eliminado.",
    sankalpa_modal_toast_delete_error: "Error al eliminar el Sankalpa.",
    
    profile_modal_title: "Completa tu Perfil Cósmico",
    profile_modal_subtitle: "Proporciona tus datos de nacimiento para que el agente Ash pueda generar ideas personalizadas de astrología y Diseño Humano.",
    profile_modal_birthdate: "Fecha de Nacimiento",
    profile_modal_birthtime: "Hora de Nacimiento",
    profile_modal_birthlocation: "Lugar de Nacimiento",
    profile_modal_birthlocation_placeholder: "Ciudad, Estado, País",
    profile_modal_gender: "Género",
    profile_modal_gender_female: "Femenino",
    profile_modal_gender_male: "Masculino",
    profile_modal_gender_other: "Otro / Prefiero no decirlo",
    profile_modal_gender_desc: "Utilizado para funciones como el seguimiento del ciclo menstrual.",
    profile_modal_toast_save_success: "¡Perfil guardado con éxito!",
    profile_modal_toast_save_error: "Error al guardar el perfil.",

    // Botones Genéricos
    button_save: "Guardar",
    button_create: "Crear",
    button_cancel: "Cancelar",
    button_delete: "Eliminar",
    button_edit: "Editar",

    // Task Connection UI
    task_connections: "Conexiones",
    task_connections_desc: "Conectar esta tarea con otras tareas",
    select_tasks_to_connect: "Seleccionar tareas para conectar",
    connected_tasks: "Tareas Conectadas",
    no_connections: "Sin conexiones",
    add_connection: "Añadir Conexión",
    remove_connection: "Eliminar Conexión",

    // Proyectos
    hub_title: "Matriz de Proyectos",
    hub_subtitle: "Vista táctica y estructural de todos tus universos",
    project_create: "Crear Proyecto",
    project_edit: "Editar Proyecto",
    project_delete: "Eliminar Proyecto",
    project_archive: "Archivar Proyecto",
    project_empty: "No hay proyectos",
    project_subprojects: "Subproyectos",
    project_tasks: "Tareas",
    project_settings: "Configuración del Proyecto",

    // === Tipo de Proyecto (Personal vs Profesional) ===
    project_type_label: "Tipo de Proyecto",
    project_personal: "Personal",
    project_personal_desc: "Solo tú lo ves",
    project_professional: "Profesional",
    project_professional_desc: "Compartir con equipo",
    project_share_team: "Compartir con equipo",
    project_select_team: "Selecciona un equipo...",

    // Templates
    save_as_template: "Guardar como Plantilla",
    template_name: "Nombre de Plantilla",
    template_description_help: "Elige exactamente qué datos quieres reutilizar en esta plantilla",
    template_field_title: "Título del Proyecto",
    template_field_description: "Descripción",
    template_field_tags: "Etiquetas",
    template_field_custom_fields: "Campos Personalizados",
    template_field_subtasks: "Estructura de Tareas",
    template_field_color: "Color",
    template_field_icon: "Icono",
    template_field_settings: "Configuración",
    select_fields_to_save: "Selecciona campos a guardar",
    template_description_placeholder: "Describe cuándo usar esta plantilla...",
    template_saved_success: "¡Plantilla guardada con éxito!",
    use_template: "Usar Plantilla",
    select_template_help: "Selecciona una de tus plantillas para crear un nuevo proyecto",
    no_templates_yet: "Aún no tienes plantillas guardadas",
    create_template_hint: "¡Crea un proyecto y guárdalo como plantilla!",
    included_data: "Datos que se incluirán:",
    new_project_name: "Nombre del nuevo proyecto",
    enter_project_name: "Ej: Proyecto Importante",
    create_from_template: "Crear desde Plantilla",
    template_use_case: "Usa esta plantilla para crear nuevos proyectos rápidamente con la misma estructura y configuración",
    template_applied: "¡Proyecto creado desde plantilla!",
    error_template_name_required: "El nombre de la plantilla es obligatorio",
    error_save_template: "Error al guardar plantilla",
    error_load_templates: "Error al cargar plantillas",
    error_apply_template: "Error al aplicar plantilla",
    error_project_name_required: "Ingresa el nombre del nuevo proyecto",
    used: "Usado",

    // Sidebar Actions
    nav_planner: "Planificador",
    nav_calendar: "Calendario",
    nav_explorer: "Explorador",
    nav_tags: "Etiquetas",
    nav_search: "Búsqueda",
    quick_idea: "Nueva Idea",
    quick_task: "Nueva Tarea",
    quick_project: "Nuevo Proyecto",
    quick_document: "Nuevo Documento",
    logout: "Cerrar Sesión",

    // Calendario
    month_view: "Vista Mensual",
    week_view: "Vista Semanal",
    day_view: "Vista Diaria",
    today_button: "Hoy",
    prev_month: "Mes Anterior",
    next_month: "Próximo Mes",
    add_event: "Añadir Evento",
    edit_event: "Editar Evento",
    delete_event: "Eliminar Evento",
    calendar_empty: "Vacío",
    calendar_no_deadline: "Sin Plazo",
    calendar_all_scheduled: "Todo programado.",
    calendar_drop_to_remove: "Suelta para eliminar fecha",
    calendar_sun: "DOM",
    calendar_mon: "LUN",
    calendar_tue: "MAR",
    calendar_wed: "MIÉ",
    calendar_thu: "JUE",
    calendar_fri: "VIE",
    calendar_sat: "SÁB",

    // Equipos
    add_member: "Añadir Miembro",
    invite_email: "Invitar por Email",
    manage_roles: "Gestionar Roles",
    leave_team: "Salir del Equipo",
    team_members: "Miembros del Equipo",
    team_settings: "Configuración del Equipo",
    invite_member: "Invitar Miembro",
    invite_guardian: "Invitar Guardián",
    members_active: "Miembros Activos & Vitalidad",
    email_collaborator: "Email del Colaborador",
    access_permission: "Permiso de Acceso",
    role_admin: "Admin (Líder)",
    role_editor: "Editor (Colaborador)",
    role_viewer: "Observador (Lector)",
    cancel: "Cancelar",
    send_invite: "Enviar Invitación",
    invite_sent: "Invitación estelar enviada a {{email}}",
    team_sync_error: "Error al sincronizar equipo.",
    gathering_council: "Reuniendo el consejo...",

    // Vistas
    kanban_board: "Tablero Kanban",
    sheet_view: "Vista de Hoja",
    mind_map: "Mapa Mental",
    chain_view: "Vista en Cadena",
    doc_editor: "Editor de Documentos",
    inbox_view: "Bandeja de Entrada",
    // Pestañas de Proyecto
    tab_overview: "Descripción General",
    tab_board: "Tablero",
    tab_sheet: "Lista",
    tab_calendar: "Programación",
    tab_map: "Mapa Mental",
    tab_nexus: "Nexus",
    tab_files: "Archivos",
    tab_team: "Equipo",
    tab_settings: "Configuración",
    // Acciones de Tarea
    add_task: "Añadir Tarea",
    edit_task: "Editar Tarea",
    delete_task: "Eliminar Tarea",
    mark_complete: "Marcar como Completado",
    add_subtask: "Añadir Subtarea",
    task_priority: "Prioridad",
    task_due_date: "Fecha de Vencimiento",
    task_assignee: "Asignado a",
    task_status: "Estado",
    task_description: "Descripción",

    // Modales y Confirmaciones
    confirm_delete: "¿Estás seguro de que deseas eliminar?",
    confirm_delete_desc: "Esta acción no se puede deshacer.",
    unsaved_changes: "Hay cambios sin guardar",
    save_changes: "Guardar Cambios",
    discard_changes: "Descartar Cambios",
    close: "Cerrar",

    // Validación
    required_field: "Campo requerido",
    invalid_email: "Email inválido",
    min_length: "Longitud mínima: {length}",
    max_length: "Longitud máxima: {length}",
    password_mismatch: "Las contraseñas no coinciden",
    success: "¡Éxito!",
    error: "Error",
    loading: "Cargando...",
    no_data: "Sin datos disponibles",

    // Configuración
    appearance: "Apariencia",
    account_region: "Cuenta y Región",
    animations: "Animaciones de Interfaz",
    animations_desc: "Efectos de partículas y transiciones suaves.",
    system_language: "Idioma del Sistema",
    logout_session: "Cerrar Sesión",
    ash_brain: "Cerebro de Ash",
    main_role: "Rol Principal",
    main_role_desc: "Ej: Senior React Dev, Copywriter, Mentor...",
    voice_tone: "Tono de Voz",
    voice_tone_desc: "Ej: Directo, Socrático, Divertido, Formal...",
    tech_stack: "Stack Tecnológico / Contexto",
    tech_stack_desc: "Ej: React, Tailwind, Node.js, Drizzle ORM",
    custom_instructions: "Instrucciones Personalizadas (Ley Suprema)",
    custom_instructions_desc: "Ej: Siempre explica el 'por qué' antes del código...",
    update_brain: "Actualizar Cerebro",
    tuning: "Sintonizando...",

    // Kanban
    kanban_add_note: "Añadir Nota",
    kanban_todo: "Por Hacer",
    kanban_in_progress: "En Progreso",
    kanban_blocked: "Bloqueado",
    kanban_done: "Completado",

    // Inbox (Chispas)
    inbox_title: "Bandeja de Entrada",
    inbox_subtitle: "Captura, procesa y vacía tu mente.",
    inbox_zero: "Bandeja Vacía",
    inbox_zero_desc: "Tu mente está limpia. Usa el atajo Ctrl+K para capturar nuevas ideas.",
    promote_to_task: "Promover a Tarea",
    promote_to_project: "Promover a Proyecto",
    promoted_to_task: "¡Promovido a Tarea!",
    promoted_to_project: "¡Expandido a Proyecto!",
    promoted_to_task_error: "Error al promover.",
    inbox_empty_error: "Error al descartar.",
    inbox_loading: "Sintonizando pensamientos...",
    inbox_error: "Error al cargar la Bandeja.",

    // Sheet View
    sheet_title: "Hoja",
    sheet_items_count: "Elementos",
    sheet_filter_placeholder: "Filtrar...",
    sheet_show_columns: "Mostrar",
    sheet_columns: "Columnas",
    sheet_new_subtask: "Nueva Subtarea",
    sheet_delete_item: "Eliminar",
    sheet_new_root_line: "Nueva Línea Raíz",
    sheet_select_project: "Selecciona un proyecto.",
    sheet_task_name: "Tarea",
    sheet_responsible: "Responsable",
    sheet_status: "Estado",
    sheet_priority: "Prioridad",
    sheet_due_date: "Fecha de Vencimiento",
    sheet_remove_confirm: "¿Eliminar elemento?",
    sheet_created: "Creado.",
    sheet_error: "Error.",
    sheet_save_error: "Fallo al guardar.",

    // Mind Map
    mindmap_add_node: "Nodo",
    mindmap_title: "Mapa Mental",
    mindmap_tuning: "Sintonizando frecuencias...",
    mindmap_saving: "Guardando...",
    mindmap_synced: "Sincronizado",
    mindmap_project_nucleus: "Núcleo del Proyecto",
    mindmap_global_consciousness: "Conciencia Global",

    // Doc Editor
    doc_editor_loading: "Abriendo el grimorio...",
    doc_editor_error_not_found: "Documento no encontrado o acceso denegado.",
    doc_editor_error_loading: "Error al cargar documento.",
    doc_editor_save_error: "Falló al guardar cambios.",
    doc_editor_saving: "Guardando...",
    doc_editor_saved_at: "Guardado a las",
    doc_editor_no_title: "Sin Título",
    doc_editor_draft: "Borrador",
    doc_editor_share: "Compartir",
    doc_editor_retry: "Intentar Nuevamente",
    doc_editor_title_updated: "Título actualizado.",
    
    // Document Type Selection
    doc_type_label: "Tipo de Documento",
    doc_type_note: "Nota",
    doc_type_diary: "Diario",
    doc_type_agreement: "Acuerdo",
    doc_type_manifest: "Manifiesto",
    doc_type_guide: "Guía",
    doc_type_other: "Otro",
    
    // Diary Fields (when documentType='diary')
    diary_energy_label: "Nivel de Energía",
    diary_energy_1: "Muy Baja",
    diary_energy_2: "Baja",
    diary_energy_3: "Media",
    diary_energy_4: "Alta",
    diary_energy_5: "Muy Alta",
    diary_mood_label: "Estado de Ánimo",
    diary_mood_calm: "Calma",
    diary_mood_joy: "Alegría",
    diary_mood_focus: "Enfoque",
    diary_mood_creativity: "Creatividad",
    diary_mood_anxiety: "Ansiedad",
    diary_mood_confusion: "Confusión",
    diary_mood_gratitude: "Gratitud",
    diary_mood_sadness: "Tristeza",
    diary_tags_label: "Etiquetas",
    diary_tags_placeholder: "Añadir etiqueta...",
    diary_insights_label: "Perspectivas Adicionales",
    diary_insights_placeholder: "Notas extra...",
    diary_private: "Privado (solo tú lo ves)",
    diary_saved_success: "¡Diario guardado correctamente!",

    // Chain View (Nexus)
    chain_loading: "Mapeando el cosmos...",
    chain_title: "Nexus",
    chain_subtitle: "Mapa de Dependencias",
    chain_error_mapping: "Error al mapear constelación.",
    chain_error_connection: "Falló la conexión.",
    chain_link_created: "Vínculo estelar creado.",
    chain_drag_to_connect: "Arrastra para conectar",

    // Planner View
    planner_title: "Matriz Temporal",
    planner_sync_error: "Falló la sincronización temporal.",
    planner_save_error: "Error al guardar movimiento.",
    planner_today: "Hoy",

    // Tag Canvas View
    tag_canvas_loading: "Mapeando #",
    tag_canvas_no_tag: "Selecciona una etiqueta",
    tag_canvas_virtual_context: "Contexto Virtual",
    tag_canvas_items: "Elementos",
    tag_canvas_related_projects: "Proyectos Relacionados",
    tag_canvas_tasks_actions: "Tareas & Acciones",
    tag_canvas_knowledge_docs: "Conocimiento (Docs)",
    tag_canvas_no_items: "Sin elementos etiquetados con #",

    // List View
    list_view_loading: "Cargando...",
    list_view_status_todo: "Por Hacer",
    list_view_status_doing: "Haciendo",
    list_view_status_review: "Revisión",
    list_view_status_done: "Completado",
    list_view_error_loading: "Error al cargar lista:",

    // Sankalpa View
    sankalpa_greeting: "¿Cuál es tu intención ahora?",
    sankalpa_create_something: "Crear Algo",
    sankalpa_search: "Buscar...",
    sankalpa_press_space: "Presiona Espacio para hablar con Ash",

    // Dashboard View  
    dashboard_intention_day: "Intención del Día",
    dashboard_today_velocity: "Velocidad (Hoy)",
    dashboard_project_matrix: "Matriz de Proyectos",
    dashboard_moon_sign: "Luna en Escorpio",
    dashboard_advice: "Lo invisible toma forma. Profundiza tus raíces.",
    dashboard_energy_summary: "Energía densa. Ideal para el enfoque.",
    dashboard_favorable_energy: "Energía favorable para la introspección.",

    // Chat View
    chat_focus_session: "Sesión de Enfoque",
    chat_new_conversation: "Nueva Conversación",
    chat_attach_file: "Adjuntar archivo",
    chat_send_message: "Conversar con Prana...",
    chat_prana_ai: "Prana AI 3.0 • OpenAI Integrado",
    
    // SideChat
    sidechat_ash_title: "Ash",
    sidechat_neural_interface: "Interfaz Neural",
    sidechat_clear_memory: "Limpiar Memoria",
    sidechat_focus_indicator: "En Enfoque",
    sidechat_context_label: "Contexto",
    sidechat_thinking: "Pensando...",
    sidechat_neural_connected: "Conexión neural establecida.",
    sidechat_awaiting_input: "Esperando entrada...",
    sidechat_placeholder_default: "Habla con Ash...",
    sidechat_placeholder_context: "Acerca de:",
    
    // Holistic Context Indicators (Nuevos)
    holistic_energy_indicator: "Energía Física",
    holistic_mood_indicator: "Estados Emocionales",
    holistic_tags_label: "Tópicos en Enfoque",
    holistic_astrology_indicator: "Cosmos",
    holistic_menstrual_indicator: "Ciclo Menstrual",
    holistic_menstrual_menstrual: "Menstrual",
    holistic_menstrual_folicular: "Folicular",
    holistic_menstrual_ovulatory: "Ovulatorio",
    holistic_menstrual_luteal: "Lútea",
    
    // Sidebar & Layout
    sidebar_explorer: "EXPLORADOR",
    sidebar_tags: "ETIQUETAS",
    sidebar_system_active: "Sistema Activo",
    sidebar_version: "v10.0 Release",
  }
};

// ============================================================================
// PROMPTS DO ASH (SISTEMA IA)
// ============================================================================
export const ashPrompts = {
  pt: {
    system_base: `Você é ASH, o Sistema Operacional Neural do Prana.`,
    system_persona: `=== SUA PERSONA ===
Papel: {{role}}
Tom: {{tone}}
{{tech_stack}}`,
    system_rules: `=== REGRAS DE OURO (S.O.C.D.) ===
1. Ações Simples: Use 'manage_hierarchy' ou 'manage_inbox' diretamente.
2. Ações Complexas/Destrutivas: Use SEMPRE 'propose_execution'. Não execute direto se for apagar algo importante ou criar uma estrutura grande.
3. Visualização: Use 'render_dynamic_ui' para responder perguntas com gráficos ou listas ricas.
4. Idioma: pt-BR.`,
    system_modes: `MODO: {{mode}}`,
    mode_organize: "ORGANIZE (Cronos)",
    mode_create: "CREATE (Criativo)",
    mode_general: "GERAL",
    
    // Tool descriptions
    tool_propose_execution: "Use esta ferramenta quando a ação for complexa, destrutiva ou criar múltiplos itens. Retorna um card de confirmação para o usuário.",
    tool_manage_hierarchy: "Cria e organiza itens (Tarefas, Projetos, Docs) na estrutura. Executa a ação imediatamente.",
    tool_navigate_view: "Navega para uma ferramenta/view específica.",
    tool_manage_inbox: "Lista, promove ou deleta itens da Inbox (Sparks).",
    tool_render_ui: "Constrói uma interface visual personalizada (Gráficos, Listas) no Canvas.",
    tool_perform_audit: "Auditoria do sistema.",
    tool_get_tags: "Lista tags existentes.",
    tool_search_knowledge: "Busca no RAG.",
  },
  en: {
    system_base: `You are ASH, Prana's Neural Operating System.`,
    system_persona: `=== YOUR PERSONA ===
Role: {{role}}
Tone: {{tone}}
{{tech_stack}}`,
    system_rules: `=== GOLDEN RULES (S.O.C.D.) ===
1. Simple Actions: Use 'manage_hierarchy' or 'manage_inbox' directly.
2. Complex/Destructive Actions: ALWAYS use 'propose_execution'. Don't execute directly if deleting something important or creating large structures.
3. Visualization: Use 'render_dynamic_ui' to answer questions with rich graphs or lists.
4. Language: en-US.`,
    system_modes: `MODE: {{mode}}`,
    mode_organize: "ORGANIZE (Cronos)",
    mode_create: "CREATE (Creative)",
    mode_general: "GENERAL",
    
    // Tool descriptions
    tool_propose_execution: "Use this tool when the action is complex, destructive, or creates multiple items. Returns a confirmation card to the user.",
    tool_manage_hierarchy: "Creates and organizes items (Tasks, Projects, Docs) in the structure. Executes immediately.",
    tool_navigate_view: "Navigates to a specific tool/view.",
    tool_manage_inbox: "Lists, promotes, or deletes items from Inbox (Sparks).",
    tool_render_ui: "Builds a custom visual interface (Charts, Lists) on Canvas.",
    tool_perform_audit: "System audit.",
    tool_get_tags: "Lists existing tags.",
    tool_search_knowledge: "Search in RAG.",
  },
  es: {
    system_base: `Eres ASH, el Sistema Operativo Neural de Prana.`,
    system_persona: `=== TU PERSONALIDAD ===
Rol: {{role}}
Tono: {{tone}}
{{tech_stack}}`,
    system_rules: `=== REGLAS DE ORO (S.O.C.D.) ===
1. Acciones Simples: Usa 'manage_hierarchy' o 'manage_inbox' directamente.
2. Acciones Complejas/Destructivas: SIEMPRE usa 'propose_execution'. No ejecutes directamente si eliminas algo importante o creas estructuras grandes.
3. Visualización: Usa 'render_dynamic_ui' para responder preguntas con gráficos o listas ricas.
4. Idioma: es-ES.`,
    system_modes: `MODO: {{mode}}`,
    mode_organize: "ORGANIZAR (Cronos)",
    mode_create: "CREAR (Creativo)",
    mode_general: "GENERAL",
    
    // Tool descriptions
    tool_propose_execution: "Usa esta herramienta cuando la acción sea compleja, destructiva o cree múltiples elementos. Devuelve una tarjeta de confirmación al usuario.",
    tool_manage_hierarchy: "Crea y organiza elementos (Tareas, Proyectos, Docs) en la estructura. Se ejecuta inmediatamente.",
    tool_navigate_view: "Navega hacia una herramienta/vista específica.",
    tool_manage_inbox: "Lista, promueve o elimina elementos de la Inbox (Sparks).",
    tool_render_ui: "Construye una interfaz visual personalizada (Gráficos, Listas) en Canvas.",
    tool_perform_audit: "Auditoría del sistema.",
    tool_get_tags: "Lista etiquetas existentes.",
    tool_search_knowledge: "Busca en RAG.",
  }
};

const LanguageContext = createContext();

export const useTranslations = () => useContext(LanguageContext);

// Helper para obter prompts do Ash
export const getAshPrompts = (language = 'pt') => {
    return ashPrompts[language] || ashPrompts['pt'];
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('pt');

    useEffect(() => {
        const savedLanguage = localStorage.getItem('prana-language') || 'pt';
        setLanguage(savedLanguage);
        document.documentElement.lang = savedLanguage;
    }, []);

    const handleSetLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('prana-language', lang);
        document.documentElement.lang = lang;
    };

    const t = (key) => {
        return (translations[language] && translations[language][key]) || translations['pt'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};